my:
  web:
    index:
      title: "-_-"
      indexContentUrl: ""
      expandAll: false
  webfilter:
    permission: false
  persistence:
    file:
      async: true


test: false

server:
   port: 9999

spring:
  application:
    name: trace
