my:
  web:
    index:
      title: "-_-"
      indexContentUrl: ""
      expandAll: false
  webfilter:
    permission: false


test: false

server:
   port: 9999

spring:
  application:
    name: trace
