my:
  web:
    index:
      title: "个人工具箱"
      indexContentUrl: ""
  webfilter:
    permission: true
  datasource:
    permission:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.2.11:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false


spring:
  application:
    name: my-tools
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always